### ISSUE TITLE
Outline v3.7.0

### ISSUE THREAD

**Issue by film42** [ruby-protobuf/protobuf#323]
Thank you @embark, @nerdrew and others for making a ton of contributions recently. You all rock! I know there are a few more PRs you want to open to complete the work you've been doing. I've been doing a poor job of reviewing code quickly, and I know it's frustrating when a project maintainer is not responsive. I feel I can change this by understanding what's coming down the pipe. So, I think we should use this issue to sync-up/ outline your remaining changes, and then split each thing out into its own issue under the `v3.7.0` milestone. It might have been better to do this earlier, but I'm learning as I go :).

cc @brianstien @liveh2o @mmmries @abrandoned

**Comment by embark** [comment]
Thanks for taking this initiative! Sorry for the late reply (my bad this time)

High level, the upcoming changes will provide an API for accessing [custom options](https://developers.google.com/protocol-buffers/docs/proto#customoptions). There are some very small API changes/fixes, so it would probably be better to make it a 4.0 release.

I should however make a note about the API changes -- I have a fork with all these upcoming changes, which has not caused any issues for any of the systems that switched from this repo to the fork. The systems make heavy use of the whole spectrum of the protobuf API, so that gives me a lot of confidence. Ultimately I hope to merge all the changes back into this repo and deprecate the fork, though.

The changes upcoming to support custom options are, in rough order:
- Fix the behavior of `Protobuf::Message.field?` and `Protobuf::Message.#{field}!` in a some edge cases of repeated fields.
- During code generation, evaluate unknown Protobuf message extensions. Custom options are defined in protobufs as extensions, so this allows us to set and access the custom option extension fields of Protobuf::Message objects such as `MethodOptions`, `MessageOptions`, `ServiceOptions`, `FieldOptions` etc during code generation.
- Add support for custom file options (generated code + read api) 
 - `::Test.get_option(:".test.file_option")`

- Add support for custom field options (generated code + read api) 
 - `::Test.field[0].get_option(:".test.field_option")`

- Add support for custom enum options (generated code + read api)
 - `::Test::Enum.get_option(:".test.enum_option")`

- Add support for custom message options (generated code + read api)
 - `::Test::Message.get_option(:".test.message_option")`

- Add support for custom service options (generated code + read api)
 - `::Test::Service.get_option(:".test.service_option")`

- Add support for custom method options (generated code + read api)
 - `::Test::Service.rpcs[:doMethod].get_option(:".test.method_option")`

I should also mention that custom options lead to some other cool features that I have queued up, such as the support of map types.

**Comment by embark** [comment]
For reference, here is the branch with most of the upcoming changes, as well as a few that have already been accepted: https://github.com/nerdrew/protobuf-gem/compare/master...piecewise-custom-descriptor-options?expand=1#files_bucket

It might in particular be interesting to refer to example generated code containing all forms of custom options:
https://github.com/nerdrew/protobuf-gem/compare/master...piecewise-custom-descriptor-options?expand=1#diff-9ad44079bb674d7b4196f4bef512a850

**Comment by film42** [comment]
@embark @nerdrew Thanks for your patience through the process of merging in your changes.

I think it would be nice to get a 3.7.0 release out soon. Would you mind commenting with another update on what's remaining? Seems like there are still a number of them, but they all seem smaller.

P.S. Sorry for being a lame maintainer. I should have a more time to dedicate to this project now. Again, thanks for contributing!

**Comment by embark** [comment]
@film42 Thanks for keeping us updated. The remaining things I'd really like to see are the support for custom options for files, fields, enums, messages, services, and methods. 

Here are example commits, though I will open up PRs for them each in order:
Files: https://github.com/nerdrew/protobuf-gem/commit/3abcbb58c2a4190d909ff6fbeaf0568ea8993709
Fields: https://github.com/nerdrew/protobuf-gem/commit/0e821bad4443b88c07be8486511a6df9dd5950e5
Enums: https://github.com/nerdrew/protobuf-gem/commit/7b66b3c4f7209252ae8143352da388bfadd1dace
Messages: https://github.com/nerdrew/protobuf-gem/commit/49da6dd2618f5325a83c51c60eb7c0ca93615278
Services: https://github.com/nerdrew/protobuf-gem/commit/5b77dedf502b1e5515b0f80a6e0c8ca372c80193
Methods: https://github.com/nerdrew/protobuf-gem/commit/7eb706d8189d6e2c0bd02d1f597f777aac65f4a7

The field options PR is slightly larger than the rest, as it sets up some framework, but they are all pretty small and mostly consist of specs.

**Comment by film42** [comment]
Great! Exciting to see this come together!

**Comment by film42** [comment]
We changed `require 'protobuf/message'` to `require 'protobuf'` here: https://github.com/ruby-protobuf/protobuf/pull/316/files#diff-eb0a50ebe47673132edfc65d4cd9a436R108

⚠️ This will cause all generated files to change. Not a big deal, but I'm dropping this comment so we can review it before the 3.7.0 release to see if it's worth the change, or if it's something we should change back.

**Comment by film42** [comment]
@embark @nerdrew that should be everything, correct? Thank you for working with us to get all of these merged.

**Comment by embark** [comment]
@film42 this is all the option work -- I'm planning to move us off our fork to test all the new changes together, but I don't anticipate changes unless the tests catch anything. Thanks so much for pushing us through on this!

We also have some code to support map types -- it doesn't have to be a part of the next release, but I'd like to get it added in the not too distant future

**Comment by film42** [comment]
Thanks @embark let's get maps types in 3.8.0. It's something I've been wanting to add as well, so thanks for doing that!

I cut a pre3 of 3.7.0 and a few services have been running in production for nearly a week without any issues. I hope all goes smooth on your side :)

**Comment by embark** [comment]
So far so good! Will followup with map types when I can.

**Comment by film42** [comment]
@embark thanks! I went ahead and released 3.7.0 stable and created a new `3-7-stable` branch as well.
