### ISSUE TITLE
none of these callback(on_complete, on_success and on_failure) were called

### ISSUE THREAD

**Issue by tzwm** [ruby-protobuf/protobuf#340]
I don't know why it happened.
I use the gem `protobuf-rpc-register`. 
There are callbacks in [this method](https://github.com/scorix/protobuf-rpc-register/blob/master/lib/protobuf/rpc/clients/base.rb#L20). And I found no callback be called even I added `on_complete`.

**Comment by mmmries** [comment]
@tzwm I think you opened this on the wrong repository. I think you intended you file an issue with scorix/protobuf-rpc-register since that is the gem you are using. This repository is for the `protobuf` gem

**Comment by tzwm** [comment]
@mmmries I'm using [scorix/protobuf-rpc-register](https://github.com/scorix/protobuf-rpc-register), but this gem is using callback by `protobuf`. I found the problem is no callback was called. And the callback is belongs to `protobuf`.

**Comment by liveh2o** [comment]
What happens when you call `send_rpc_request` without a block? If the client is configured correctly, you should get a raw Protobuf response back.

I ask because we are using this code in production today without issue. I also maintain [ActiveRemote](https://github.com/liveh2o/active_remote) which uses the callbacks in it's [Protobuf adapter](https://github.com/liveh2o/active_remote/blob/master/lib/active_remote/rpc_adapters/protobuf_adapter.rb#L17-L35), which is are also using in production without issue.

**Comment by tzwm** [comment]
Finally I found the problem is about the socket. We got the size of data by [this method](https://github.com/ruby-protobuf/protobuf/blob/master/lib/protobuf/rpc/connectors/socket.rb#L45), and read data by size. But I can't pass the [validation](https://github.com/ruby-protobuf/protobuf/blob/master/lib/protobuf/rpc/buffer.rb#L63) about size. The real size of data is smaller than data size which got from `TCPSocket#getc` before.
So `protobuf` will not run the next code if [two size is not equal](https://github.com/ruby-protobuf/protobuf/blob/master/lib/protobuf/rpc/connectors/socket.rb#L59).
